Egham-7/adaptive

adaptive_ai/api/routes/classifier.py
adaptive_ai/models/llms.py
adaptive_ai/poetry.lock
adaptive_ai/pyproject.toml
adaptive_ai/services/llm_parameters.py
adaptive_ai/services/model_selector.py

new way using vector similarity

choosing model upgrade

---

adaptive-backend/internal/models/completions.go
adaptive-backend/internal/utils/messages.go

…nRequest for backward compatibility
feat(messages.go): handle messages with tool calls but empty content to improve message extraction logic
chore(main): update binary for adaptive-backend with recent changes

feat: extract tool results for semantic cache entry to prevent errors and cache misses

---

adaptive-backend/internal/utils/messages.go

feat: extract tool results for semantic cache entry to prevent errors and cache misse

---

adaptive-backend/internal/api/completions.go
adaptive-backend/internal/models/completions.go

feat(models.go): define FallbackMode type and constants for sequential and parallel strategies in chat completion requests

feat(completions.go): add fallback mode configuration in request

---

adaptive-docs/api-reference/chat-completions.mdx
adaptive-docs/api-reference/introduction.mdx
adaptive-docs/authentication.mdx
adaptive-docs/features/intelligent-routing.mdx
adaptive-docs/features/performance.mdx
adaptive-docs/index.mdx
adaptive-docs/integrations/langchain.mdx
adaptive-docs/integrations/openai-sdk.mdx
adaptive-docs/integrations/vercel-ai-sdk.mdx
adaptive-docs/quickstart.mdx
adaptive-docs/troubleshooting.mdx

feat: update docs (#323)

---

adaptive-app/src/app/_components/api-platform/onboarding/api-key-step.tsx
adaptive-app/src/app/_components/api-platform/onboarding/complete-step.tsx
adaptive-app/src/app/_components/api-platform/onboarding/organization-step.tsx
adaptive-app/src/app/_components/api-platform/onboarding/project-step.tsx
adaptive-app/src/app/_components/api-platform/onboarding/quickstart-step.tsx
adaptive-app/src/app/_components/api-platform/onboarding/welcome-step.tsx
adaptive-app/src/app/_components/api-platform/organizations/credit-management.tsx
adaptive-app/src/app/api-platform/onboarding/page.tsx
adaptive-app/src/app/api-platform/organizations/[orgId]/projects/[projectId]/api-keys/page.tsx
adaptive-app/src/app/api-platform/organizations/[orgId]/projects/[projectId]/quickstart/page.tsx
adaptive-app/src/app/api-platform/organizations/page.tsx
adaptive-app/src/components/ui/code-block.tsx
adaptive-app/src/components/ui/quickstart-examples.tsx
adaptive-app/src/hooks/use-smart-redirect.ts
adaptive-app/src/lib/cache-utils.ts
adaptive-app/src/lib/redis.ts

feat: add quick start to onboarding

---

adaptive-app/src/app/_components/api-platform/organizations/projects/project-sidebar.tsx
adaptive-app/src/app/api-platform/organizations/[orgId]/projects/[projectId]/layout.tsx

feat(project-sidebar): create new project sidebar component for project-level navigation
feat(project-layout): add layout for project pages to include project sidebar

feat(organization-sidebar): simplify organization sidebar by removing project-level navigation and updating links

---

adaptive-app/src/app/_components/api-platform/organizations/projects/dashboard/cost-comparison.tsx
adaptive-app/src/app/_components/api-platform/organizations/projects/dashboard/provider-comparison-table.tsx

feat: remove too many layers of cards in cost comparison

---

adaptive-backend/cmd/api/main.go
adaptive-backend/internal/api/completions.go
adaptive-backend/internal/config/config.go
adaptive-backend/internal/models/cache_config.go
adaptive-backend/internal/models/fallback.go
adaptive-backend/internal/models/prompt_cache.go
adaptive-backend/internal/services/cache/prompt_cache.go
adaptive-backend/internal/services/fallback/fallback_service.go
adaptive-docs/api-reference/chat-completions.mdx
adaptive-docs/features/prompt-response-cache.mdx
adaptive-docs/features/provider-resiliency.mdx

feat: change prompt response cache to use semantic cache

---

adaptive-app/prisma/migrations/20250823211627_make_api_key_nullable/migration.sql
adaptive-app/prisma/schema.prisma
adaptive-app/src/app/_components/api-platform/organizations/projects/dashboard/cost-comparison.tsx
adaptive-app/src/app/_components/api-platform/organizations/projects/dashboard/model-selector.tsx
adaptive-app/src/app/api-platform/(organization)/organizations/[orgId]/page.tsx
adaptive-app/src/app/api-platform/(projects)/organizations/[orgId]/projects/[projectId]/page.tsx
adaptive-app/src/components/organization-breadcrumb.tsx
adaptive-app/src/components/project-breadcrumb.tsx
adaptive-app/src/components/ui/multiple-selector.tsx
adaptive-app/src/hooks/organizations/use-organization.ts
adaptive-app/src/server/api/routers/usage.ts

Debug charts (#416)

---

adaptive-app/src/app/api-platform/(projects)/organizations/[orgId]/projects/[projectId]/quickstart/page.tsx
adaptive-app/src/app/api/v1/chat/completions/route.ts
adaptive-app/src/app/api/v1/select-model/route.ts
adaptive-app/src/lib/pricing-config.ts
adaptive-app/src/server/api/routers/usage/usage-recording.ts
adaptive-app/src/types/chat-completion.ts

Feat/charge select model + charge cache tiers (#441)

---

.github/workflows/backend-ci.yml
.github/workflows/backend-dev-ci.yml
adaptive-backend/go.mod
adaptive-backend/go.sum
adaptive-backend/internal/api/completions.go
adaptive-backend/internal/api/messages.go
adaptive-backend/internal/api/select-model.go
adaptive-backend/internal/config/config.go
adaptive-backend/internal/models/cache_config.go
adaptive-backend/internal/services/api_client.go
adaptive-backend/internal/services/cache/prompt_cache.go
adaptive-backend/internal/services/chat/completions/completions.go
adaptive-backend/internal/services/chat/completions/response.go
adaptive-backend/internal/services/format_adapter/adaptive_to_anthropic.go
adaptive-backend/internal/services/model_router/model_router_cache.go
adaptive-backend/internal/services/model_router/router.go
adaptive-backend/internal/services/select_model/service.go
adaptive-backend/internal/services/stream_readers/stream/stream.go

feat: upgrade semanticcache to v0.3.0 (#467)

---

adaptive-app/src/app/api/v1/chat/completions/route.ts
adaptive-app/src/app/api/v1/clusters/[projectId]/[name]/chat/completions/route.ts
adaptive-app/src/app/api/v1/clusters/[projectId]/[name]/messages/route.ts
adaptive-app/src/app/api/v1/messages/route.ts
adaptive-app/src/types/anthropic-messages.ts
adaptive-backend/internal/models/completions.go
adaptive-backend/internal/models/model_capability.go
adaptive-backend/internal/services/anthropic/messages/messages.go
adaptive-backend/internal/services/cache/stream_converter.go
adaptive-backend/internal/services/chat/completions/completions.go
adaptive-backend/internal/services/format_adapter/adaptive_to_openai.go
adaptive-backend/internal/services/format_adapter/anthropic_to_adaptive.go
adaptive-backend/internal/services/format_adapter/openai_to_adaptive.go
adaptive-backend/internal/services/stream_readers/sse/anthropic.go
adaptive-backend/internal/services/stream_readers/sse/openai.go
adaptive-backend/internal/services/stream_readers/stream/stream.go
adaptive-docs/api-reference/chat-completions.mdx
adaptive-docs/api-reference/select-model.mdx
adaptive-docs/docs.json
adaptive-docs/examples/basic-chat.mdx
adaptive-docs/examples/select-model.mdx
adaptive-docs/examples/streaming-chat.mdx
examples/ts/examples/basic-anthropic.ts
examples/ts/examples/basic-openai.ts
examples/ts/examples/basic-select-model.ts
examples/ts/examples/basic-vercel-ai-sdk.ts

fix: openai & anthropic streaming compatibility (#469)

---

adaptive_ai/adaptive_ai/main.py
adaptive_ai/adaptive_ai/models/llm_core_models.py
adaptive_ai/adaptive_ai/services/model_registry.py
adaptive_ai/adaptive_ai/services/model_router.py
adaptive_ai/tests/test_partial_model_handling.py
adaptive_ai/tests/test_task_specialization.py

Fix model parameters and tests  (#473)

---

adaptive-backend/cmd/api/main.go
adaptive-backend/internal/services/circuitbreaker/circuit_breaker.go
adaptive-backend/internal/services/model_router/client.go
claude-code.sh

feat: add circuit breaker per provider

---

adaptive-backend/internal/models/model_capability.go
adaptive-backend/internal/models/model_router.go
adaptive-backend/internal/services/model_router/client.go
adaptive_ai/model_router/model_data/data/provider_models/anthropic_models_structured.yaml
adaptive_ai/model_router/model_router/services/model_registry.py

feat: add omitzero to model capability type

---

adaptive-docs/developer-tools/opencode.mdx
scripts/installers/opencode.sh

feat: add opencode installer

---

adaptive-backend/config.yaml

fix: gemini openai compatible provider endpoint

---

adaptive-backend/config.yaml
scripts/installers/opencode.sh

fix: gemini openai compatible endpoint

---

scripts/installers/claude-code.sh
scripts/installers/codex.sh
scripts/installers/grok-cli.sh
scripts/installers/opencode.sh

feat(backup): add create_config_backup function to create backups of configuration files across multiple installer scripts

---

adaptive-app/bun.lock
adaptive-app/package.json
adaptive-backend/go.mod
adaptive-backend/go.sum

chore: update deps

---

adaptive-docs/developer-tools/qwen-code.mdx

docs(qwen-code.mdx): fix formatting for docs

---

adaptive-backend/internal/api/gemini/count_tokens.go
adaptive-backend/internal/config/config.go

feat(gemini): add specific config resolution for count_tokens endpoint and update references to improve clarity and functionality

---

adaptive-backend/internal/api/gemini/count_tokens.go

refactor(count_tokens.go): streamline model parameter handling by improving parsing logic and adding fallback to model router

---

adaptive-app/src/app/_components/landing_page/mobile-header.tsx
adaptive-app/src/app/_components/logo.tsx

feat(logo): enhance Logo component with customizable image size and text display options for better flexibility in usage

---

adaptive-backend/cmd/api/main.go
adaptive-backend/go.mod
adaptive-backend/internal/services/anthropic/messages/messages.go
adaptive-backend/internal/services/chat/completions/completions.go
adaptive-backend/internal/services/circuitbreaker/circuit_breaker.go
adaptive-backend/internal/services/gemini/count_tokens/count_tokens.go
adaptive-backend/internal/services/gemini/generate/generate.go
adaptive-backend/internal/utils/clientcache/clientcache.go

feat(api): implement request timeout middleware with clamping and adding client cache for services to enhance performance and resource management

---

adaptive-backend/cmd/api/main.go
adaptive-backend/internal/api/health.go

feat: add health endpoint adaptive backend

---

adaptive-backend/go.mod
adaptive-backend/internal/services/model_router/router.go

chore(go.mod): update Go version to 1.25.0 and add golang.org/x/sync dependency for improved functionality

---

adaptive-app/src/lib/stripe/stripe.ts

fix(stripe.ts): update Stripe API version from 2025-08-27.preview to 2025-09-30.clover to ensure compatibility with the latest features and fixes

---

adaptive-backend/internal/services/anthropic/messages/messages.go
adaptive-backend/internal/services/chat/completions/completions.go
adaptive-backend/internal/services/gemini/generate/generate.go
adaptive-backend/internal/services/stream/readers/openai.go

fix: use separate context for separate request to fix early termination

---

adaptive-backend/internal/services/fallback/fallback_service.go
adaptive-backend/internal/services/model_router/router.go

…llback execution to improve traceability
feat(router.go): add detailed logging for model selection response and alternatives to provide better insights into AI service selection

feat(fallback_service.go): enhance logging for sequential and race fallback execution to improve traceability

---

adaptive-backend/internal/services/fallback/fallback_service.go

fix(fallback_service.go): improve timeout handling in executeStreamingRace method to differentiate between actual timeout and early completion

---

adaptive-backend/internal/api/gemini/generate.go
adaptive-backend/internal/api/messages.go
adaptive-backend/internal/services/chat/completions/completions.go

feat(messages): add primary provider execution logic with fallback alternatives to enhance reliability
feat(completions): introduce primary provider execution with fallback alternatives for improved robustness

feat(gemini): implement primary provider execution with fallback alternatives for better error handling

---

.github/workflows/model-router-ci.yml
.github/workflows/model-router-dev-ci.yml
adaptive_router/pyproject.toml
adaptive_router/scripts/README.md
adaptive_router/scripts/sync_openrouter_models.py
adaptive_router/uv.lock

fix: downgrade CI to 3.12 for torch compatibility
